server:
  port: 8089

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username:
    password:
mybatis:
  type-aliases-package: com.feitian.trade.sync.model

taobao:
  refreshTokenUrl: 'http://container.open.taobao.com/container/refresh'
  tbPostSessionUrl: ''
  topBoxApiUrl: ''
  topSecurityUrl: ''
  topBoxAutUrl: ''
  topBoxAppKey: ''
  topBoxAppSecret: ''
  redirectUri: ''
  topBoxAppKeyForBuyer: ''
  topBoxAppSecretForBuyer: ''
  topToken: ''
